version: '3.8'


# Пока что только для одно сервиса

services:
  postgres:
    image: postgres:17-alpine
    container_name: book-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: book-auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_ADDRESS=:8080
      - ENVIRONMENT=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/auth_service?sslmode=disable
      - JWT_SECRET=secret-key
      - JWT_REFRESH_SECRET=refresh-secret-key
      - JWT_EXPIRY_MINUTES=60
      - JWT_REFRESH_EXPIRY_DAYS=7
      - DB_MAX_IDLE_CONNS=10
      - DB_MAX_OPEN_CONNS=100
      - DB_CONN_MAX_LIFETIME=300
      - CORS_ALLOW_ORIGINS=*
      - CREATE_DEFAULT_ADMIN=true
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data:
